<a href="https://colab.research.google.com/github/AOKuczera/data-science-bootcamp/blob/main/Wprowadzenie/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Instalacja 


In [1]:
pip install numpy 


In [3]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [ ]:
### 1D Array 
x = np.array([[1],[3]])
x

array([[1],
       [3]])

In [ ]:
print(x)

[[1]
 [3]]


In [ ]:
type(x) #typ

numpy.ndarray

In [ ]:
# An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size

In [ ]:
#ndim - wymiar 
x.ndim

2

In [ ]:
#shape - kształt (wiersze, kolumny)
x.shape

(2, 1)

In [ ]:

# x.size - liczba elementów
x.size

2

In [ ]:
# x.dtype - typ danych
x.dtype

dtype('int64')

In [ ]:
y = np.array([1.1,2.2,3.3])

In [ ]:
y.dtype

dtype('float64')

In [ ]:
### 2D Array 
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(y)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
y.shape

(3, 3)

In [ ]:
y.ndim

2

In [ ]:
x.size

6

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

2

In [ ]:
### 3d array
x = np.array(
    [[[4,3,2],
      [1,2,3]],
     
     [[1,2,3],
      [1,2,3]]]
)
print(x)


[[[4 3 2]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [ ]:
x.ndim
a,b,c =x.shape

In [ ]:
print(a)
print(b)
print(c)

2
2
3


In [ ]:
### Tyoy danych
A = np.array([1,3,4])
A.dtype

dtype('int64')

In [ ]:
B = np.array([1.3,2.4])
B.dtype

dtype('float64')

In [ ]:
C = np.array([1.3,2.4], dtype = 'float')
C.dtype

dtype('float64')

In [ ]:
D = np.array([1.3,2.4], dtype = 'complex')
D.dtype
D

array([1.3+0.j, 2.4+0.j])

In [ ]:
E = np.array([True, False])
E.dtype ## bool - logiczne dane

dtype('bool')

In [ ]:
F = np.array([24,120,230],dtype=np.int8) ### do zachowania obrazów

In [ ]:
G = np.array([24,120,230],dtype=np.uint8) ### do zachowania obrazów

In [ ]:
### Tworzenie tablic
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(5
                ,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,6),  fill_value=5, order='F')

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [ ]:
np.full((3,3), [1,2,3],'float')

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(start=1, stop=25, step=5)

array([ 1,  6, 11, 16, 21])

In [ ]:
np.arange(start=25, stop=1, step=-5)

array([25, 20, 15, 10,  5])

In [ ]:
np.linspace(start=1, stop=10,num=9) #od start do stop

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [ ]:
A = np.arange(1,101,9)

In [ ]:
A.shape

(12,)

In [ ]:
A.reshape((3,4))
A.reshape((3,-1))#python dopier odpowiednia ilosc kolumn -1


array([[  1,  10,  19,  28],
       [ 37,  46,  55,  64],
       [ 73,  82,  91, 100]])

In [ ]:
A = np.array([1,2,3,4])

In [ ]:
B = np.array([-1,-3,4,5])

In [ ]:
A + B

array([ 0, -1,  7,  9])

In [ ]:
A - B


array([ 2,  5, -1, -1])

In [ ]:
A * B

array([-1, -6, 12, 20])

In [ ]:
A / B


array([-1.        , -0.66666667,  0.75      ,  0.8       ])

In [ ]:
A + 3 ### odjać, mnożyć, dzielić 

array([4, 5, 6, 7])

In [ ]:
np.add(A,B) #dodawanie
np.subtract(A,B)#odejmowanie
np.multiply(A,B)#mnożenie
np.divide(A,B)#dzielenie

array([-1.        , -0.66666667,  0.75      ,  0.8       ])

In [ ]:
X = np.array([[1,2],[3,4]])
Y = np.array([[-1,0],[5,3]])

In [ ]:
#mnożenie macierzy - brak przemienność
np.dot(X,Y)
X.dot(Y)
X @ Y 

array([[ 9,  6],
       [17, 12]])

In [ ]:
#ziarno losowania
np.random.seed(0)


In [ ]:
np.random.randn(10,4) #wiersze (liczba probek), kolumny # z rozdzialu normalnego


array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [ ]:
#random.rand()
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
np.random.rand(10,4)

array([[0.31542835, 0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805, 0.09394051]])

In [ ]:
#random.randint(low, high=None, size=None, dtype=int)
np.random.randint(-5,10,10)

array([-4, -1,  5,  1,  6,  3,  6, -3, -2, -5])

In [ ]:
np.random.choice(['python','java','bkaka'])

'python'

In [ ]:
np.random.choice([1,2,3])

3

In [ ]:
data = np.arange(10)
np.random.shuffle(data) #mieszanienp.

In [ ]:
data

array([1, 5, 4, 9, 7, 2, 8, 3, 6, 0])

In [ ]:
#numpay funcje
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([1,0]) # czy wszystkie sa true

False

In [ ]:
np.any([0]) #czy jakakolwiek jest true


False

In [ ]:
bool()#wartosc logiczna obiektu

False

In [ ]:
A = np.random.rand(5)#rozkład jednostajny

In [ ]:
A

array([0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191])

In [ ]:
#wartość indeksu największa np.argmax()
A[np.argmax(A),]

0.7037372792899163

In [ ]:
A[np.argmin(A),]

0.14644176272911225

In [ ]:
np.argsort(A)

array([1, 4, 0, 2, 3])

In [ ]:
np.max(A)

0.7037372792899163

In [ ]:
np.min(A)

0.14644176272911225

In [ ]:
np.mean(A)

0.4156163955478408

In [ ]:
np.median(A)

0.36980809274834003

In [ ]:
A = np.arange(20)

In [ ]:
#A[indx] - konkret, A[[,]] - dwa lub więcej 

A[1]
#A[start:stop] - przediał 
A[0:3]
#A[:stop]
A[:4]
#A[start:]
A[3:]
#A[-1] od końca
A[-2]
A[[0,3]]

array([0.89155444, 0.97857093])

In [4]:
A=np.arange(20)
np.random.shuffle(A)
A=A.reshape(4,-1)
A

array([[15, 17,  9,  2,  1],
       [12,  7,  0, 18, 11],
       [14, 19,  4,  6, 10],
       [ 5, 16,  8,  3, 13]])

In [ ]:
#Wycinanie wiersza
A[0]

array([13,  7,  5,  3, 15])

In [ ]:
#wycinanie kolumny
A[:,1]

array([ 9, 19, 17,  7])

In [ ]:
#wycinanie elementu
A[1,3]

18

In [ ]:
np.max(A)
B = np.arange(10)
np.where(A == np.min(A)) #znajdowanie indexu wartosci

(array([3]), array([3]))

In [ ]:
A[1:3,1:4]

array([[19,  3, 18],
       [17,  1, 10]])

In [ ]:
np.where(A == 7)

(array([3]), array([1]))

In [ ]:
A[3,1] = 21 #przypisywanie nowych wartości

In [ ]:
A

array([[ 5,  9,  2, 11, 12],
       [ 6, 19,  3, 18, 15],
       [ 4, 17,  1, 10, 13],
       [16, 21,  8,  0, 14]])

In [ ]:
#iteracja po wierszy 
for row in A:
  print(row)

[ 5  9  2 11 12]
[ 6 19  3 18 15]
[ 4 17  1 10 13]
[16 21  8  0 14]


In [ ]:
np.where(A == 0)

(array([3]), array([3]))

In [ ]:
A[3,3]=1

In [5]:
for row in A:
  print(row)

[15 17  9  2  1]
[12  7  0 18 11]
[14 19  4  6 10]
[ 5 16  8  3 13]


In [7]:
for row in A:
  print(row[0]) #printowanie indeksu 0 z każdego wiersza

17
7
19
16


In [8]:
for row in A:
  print(max(row)) #wyświetlanie wartośći maksymalnych

17
18
19
16


In [9]:
for row in A:
  print(row[:3])  #wyświetlanie trzech pierwszych wartości w wierszach

[15 17  9]
[12  7  0]
[14 19  4]
[ 5 16  8]


In [14]:
for a in A.flat: ### iteracja po każdym elemencie tablicy
  print(a)

15
17
9
2
1
12
7
0
18
11
14
19
4
6
10
5
16
8
3
13


In [15]:
### zmiana rozmiaru tablic
A.shape

(4, 5)

In [16]:
A.reshape(2,-1)

array([[15, 17,  9,  2,  1, 12,  7,  0, 18, 11],
       [14, 19,  4,  6, 10,  5, 16,  8,  3, 13]])

In [17]:
A.reshape(5,-1)

array([[15, 17,  9,  2],
       [ 1, 12,  7,  0],
       [18, 11, 14, 19],
       [ 4,  6, 10,  5],
       [16,  8,  3, 13]])

In [18]:
A.reshape(1,-1)

array([[15, 17,  9,  2,  1, 12,  7,  0, 18, 11, 14, 19,  4,  6, 10,  5,
        16,  8,  3, 13]])

In [21]:
A.ravel() # zamiana array into one demension list

array([15, 17,  9,  2,  1, 12,  7,  0, 18, 11, 14, 19,  4,  6, 10,  5, 16,
        8,  3, 13])

In [23]:
A.reshape(5,-1)

array([[15, 17,  9,  2],
       [ 1, 12,  7,  0],
       [18, 11, 14, 19],
       [ 4,  6, 10,  5],
       [16,  8,  3, 13]])

In [24]:
A.T #transponacja macierzy


array([[15, 12, 14,  5],
       [17,  7, 19, 16],
       [ 9,  0,  4,  8],
       [ 2, 18,  6,  3],
       [ 1, 11, 10, 13]])

In [35]:
A = np.arange(start=-10, stop=10, step=0.5 )

In [33]:
A.shape

(44,)

In [36]:
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [37]:
A > 0


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [38]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [40]:
A[np.bitwise_and(A>-5, A<4)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5])